//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListEntity
    {
        public int idList { get; set; }
        public int idUser { get; set; }
        public string idProductName { get; set; }
        public string Name { get; set; }
    }
}
