//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFCeEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NFCeEntity()
        {
            this.TB_USER_SCAN = new HashSet<UserScanEntity>();
        }
    
        public int idUser { get; set; }
        public int idScan { get; set; }
        public string idNF { get; set; }
        public int StoreCNPJ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserScanEntity> TB_USER_SCAN { get; set; }
    }
}
