//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        public int idStore { get; set; }
        public int idProduct { get; set; }
        public int idCategory { get; set; }
        public string ProductImportCode { get; set; }
        public string ProductImportName { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public System.DateTime LastUpdtDt { get; set; }
        public string LastUpdtHr { get; set; }
        public bool AllBranch { get; set; }
        public int QtdeOk { get; set; }
        public int QtdeNok { get; set; }
    }
}
