//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductEntity()
        {
            this.TB_USER_SCAN = new HashSet<UserScanEntity>();
        }
    
        public int idStore { get; set; }
        public int idProduct { get; set; }
        public int idCategory { get; set; }
        public string ProductNameImport { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public DateTime LastUpdtDt { get; set; }
        public string LastUpdtHr { get; set; }
        public bool AllBranch { get; set; }
        public int QtdeOk { get; set; }
        public int QtdeNok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserScanEntity> TB_USER_SCAN { get; set; }
    }
}
