//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntity
    {
        public int idUser { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Picture { get; set; }
        public string Email { get; set; }
        public int CPF { get; set; }
        public int CNPJ { get; set; }
        public string Hash { get; set; }
    }
}
